# Generated by Django 4.0.3 on 2022-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_riot_account_id_customuser_riot_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='riot_summoner_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
