# Generated by Django 4.0.3 on 2022-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_riot_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='riot_revison_date',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
