# Generated by Django 4.0.3 on 2022-04-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_riot_revison_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='riot_revison_date',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
