# Generated by Django 4.0.3 on 2022-04-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_riot_revison_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='riot_revison_date',
            new_name='riot_revision_date',
        ),
    ]
