# Generated by Django 4.0.3 on 2022-04-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riot_api', '0003_remove_summonersimpledataflex_user_and_more'),
        ('accounts', '0008_rename_riot_revison_date_customuser_riot_revision_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_data_flex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='riot_api.summonersimpledataflex'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_data_solo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='riot_api.summonersimpledatasolo'),
        ),
    ]
