# Generated by Django 4.0.3 on 2022-04-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riot_api', '0002_remove_summonersimpledataflex_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summonersimpledataflex',
            name='user',
        ),
        migrations.RemoveField(
            model_name='summonersimpledatasolo',
            name='user',
        ),
    ]
